server:
  port: 8080

spring:
  application:
    name: oauth2-server
  datasource:
    url: jdbc:mysql://dev.ct7r3ulfla0v.ap-northeast-1.rds.amazonaws.com:3306/mask_dev?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: mask
    password: n6vVsh0RlKJZTNV7C48agGno1